app_forgot_password_request:
    path: /
    controller: Cooolinho\Bundle\SecurityBundle\Controller\ResetPasswordController::request

app_forgot_password_check_mail:
    path: /check-email
    controller: Cooolinho\Bundle\SecurityBundle\Controller\ResetPasswordController::checkEmail

app_forgot_password_reset:
    path: /reset
    controller: Cooolinho\Bundle\SecurityBundle\Controller\ResetPasswordController::reset
