services:
    _defaults:
        autowire: true
        autoconfigure: true

    Cooolinho\Bundle\SecurityBundle\:
        resource: '../../../src/*'
        exclude: '../../../src/{DependencyInjection,Resources,Tests}'

    Cooolinho\Bundle\SecurityBundle\Controller\:
        resource: '../../../src/Controller'
        tags: ['controller.service_arguments']

    Cooolinho\Bundle\SecurityBundle\EventListener\UserListener:
        class: Cooolinho\Bundle\SecurityBundle\EventListener\UserListener
        tags:
            - { name: doctrine.orm.entity_listener, event: prePersist, entity: 'Cooolinho\Bundle\SecurityBundle\Entity\User' }
